[package]
name = "compact_strings"
version = "1.0.0"
edition = "2021"
description = "A cache-friendly but limited representation of a list of strings."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Vonr/compact_strings"
repository = "https://github.com/Vonr/compact_strings"
include = ["src/**/*", "README.md"]
rust-version = "1.56.1"
